[package]
name = "docker_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.18.1"
tokio = { version = "1.43.0",features = ["full"] }
futures = "0.3.31"
lettre = "0.11.13"
log4rs = "1.3.0"
log = "0.4.25"
